#variables


In [3]:
a=5.87

print(a)
print(type(a))

5.87
<class 'float'>


In [4]:
x="suvetha"
y= 'suvetha'
print(type(x))
z="5.87"
print(type(z))

<class 'str'>
<class 'str'>


In [9]:
x=4
y=2
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x//y)
print(x%y)

6
2
8
2.0
2
0


In [ ]:
<
>
==
>=
<=
!=

In [10]:
print(x)
print("x")

4
x


In [1]:
x = 5
y = '5'
z = x+y
print(z)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [7]:
count = 0
for i in range(1500,2701):
    if i%7==0 and i%5 == 0:
        print(i,end=',')
        count += 1
#print(f"\ntotal number:",count)
#print(f"total number:",count)
#print("total number:",count)
print("\ntotal number:",count)

1505,1540,1575,1610,1645,1680,1715,1750,1785,1820,1855,1890,1925,1960,1995,2030,2065,2100,2135,2170,2205,2240,2275,2310,2345,2380,2415,2450,2485,2520,2555,2590,2625,2660,2695,
total number: 35


In [8]:
for i in range(10):
    if i == 5:
        #print(i)
        continue
    print(i)

0
1
2
3
4
6
7
8
9


In [3]:
for i in range(1,10):
    if i == 5:
        #print(i)
        break
    print(i)

1
2
3
4


In [10]:
for i in range(1500,2701):
    if i%7==0:
        if i%5==0:
            print(i,end=' ')
print("\n total number:", count)

1505 1540 1575 1610 1645 1680 1715 1750 1785 1820 1855 1890 1925 1960 1995 2030 2065 2100 2135 2170 2205 2240 2275 2310 2345 2380 2415 2450 2485 2520 2555 2590 2625 2660 2695 
 total number: 35


In [11]:
#vowels
x= "aeroplane"
r= ['a','e','i','o','u']
for i in x:
    if i in r:
        print(i)

a
e
o
a
e


In [12]:
%whos


Variable   Type    Data/Info
----------------------------
a          int     5
count      int     35
i          str     e
r          list    n=5
x          str     aeroplane


In [13]:
a= 5+6j
b=10
c=20
%whos

Variable   Type       Data/Info
-------------------------------
a          complex    (5+6j)
b          int        10
c          int        20
count      int        35
i          str        e
r          list       n=5
x          str        aeroplane


In [14]:
def add(a,b):
    c=a+b
    print(c)
add(45,76)


121


In [15]:
%whos

Variable   Type        Data/Info
--------------------------------
a          complex     (5+6j)
add        function    <function add at 0x000001ABCF6318A0>
b          int         10
c          int         20
count      int         35
i          str         e
r          list        n=5
x          str         aeroplane


In [16]:
del add

In [17]:
%whos

Variable   Type       Data/Info
-------------------------------
a          complex    (5+6j)
b          int        10
c          int        20
count      int        35
i          str        e
r          list       n=5
x          str        aeroplane


In [18]:
add(75,85)

NameError: name 'add' is not defined

In [19]:
b=29

In [20]:
%whos

Variable   Type       Data/Info
-------------------------------
a          complex    (5+6j)
b          int        29
c          int        20
count      int        35
i          str        e
r          list       n=5
x          str        aeroplane


In [21]:
del b

In [22]:
%whos

Variable   Type       Data/Info
-------------------------------
a          complex    (5+6j)
c          int        20
count      int        35
i          str        e
r          list       n=5
x          str        aeroplane


In [23]:
a=12
b=454

c=a+b
print(c)

466


In [24]:
id(b)

1837443858928

In [25]:
count = 0
for i in range(1500,2701):
    if i%7==0 & i%5 == 0:
        print(i,end=',')
        count += 1
        
print("/n total number:", count)

1505,1512,1519,1526,1533,1540,1547,1554,1561,1568,1575,1582,1589,1596,1603,1610,1617,1624,1631,1638,1645,1652,1659,1666,1673,1680,1687,1694,1701,1708,1715,1722,1729,1736,1743,1750,1757,1764,1771,1778,1785,1792,1799,1806,1813,1820,1827,1834,1841,1848,1855,1862,1869,1876,1883,1890,1897,1904,1911,1918,1925,1932,1939,1946,1953,1960,1967,1974,1981,1988,1995,2002,2009,2016,2023,2030,2037,2044,2051,2058,2065,2072,2079,2086,2093,2100,2107,2114,2121,2128,2135,2142,2149,2156,2163,2170,2177,2184,2191,2198,2205,2212,2219,2226,2233,2240,2247,2254,2261,2268,2275,2282,2289,2296,2303,2310,2317,2324,2331,2338,2345,2352,2359,2366,2373,2380,2387,2394,2401,2408,2415,2422,2429,2436,2443,2450,2457,2464,2471,2478,2485,2492,2499,2506,2513,2520,2527,2534,2541,2548,2555,2562,2569,2576,2583,2590,2597,2604,2611,2618,2625,2632,2639,2646,2653,2660,2667,2674,2681,2688,2695,/n total number: 171


In [7]:
for i in range(1,10):
    if i == 5:
        #print(i)
        pass
        #print(i)
    print(i)

1
2
3
4
5
6
7
8
9


In [27]:
for number in range(10):
    #print(number)
    if number == 5:
        #print(number)
        break  # Stop the loop when number equals 5
    elif number % 2 == 0:
        #print(number)
        continue  # Skip even numbers
    print(number)  # Prints only odd numbers less than 5


1
3


In [28]:
%who

a	 b	 c	 count	 i	 number	 r	 x	 


In [32]:
%whos

Variable   Type    Data/Info
----------------------------
a          int     5
b          int     454
c          int     466
count      int     171
i          int     9
number     int     5
r          list    n=5
x          str     aeroplane


In [30]:
5
id(5)


140723804869544

In [31]:
a=5
id(a)

140723804869544

In [3]:
x = True
y = False
result = x and y
print(result)

False


In [6]:
x = True  
y = False  
result = x & y 
print(result)

False


In [9]:
x = 5  # In binary: 101
y = 3  # In binary: 011
result = x & y 
print(result)

1


In [7]:
x = 5
y = 3
result = x and y
print(result)

3


In [11]:
x = 0
y = 3
result = x and y
print(result)

0


In [16]:
a='suvetha'
#a.reverse()
a[-1:0]

''

In [19]:
a='suvetha'
a[:-1]

'suveth'

In [20]:
a='suvetha'
a[::-1]

'ahtevus'

In [22]:
a[0:4]

'suve'

In [23]:
a[0:]

'suvetha'

In [24]:
a[::]

'suvetha'

In [25]:
a=123
a[1]

TypeError: 'int' object is not subscriptable

In [26]:
num=1234
last_num = num%10
reverse_num = 0 * 10 + last_num
num = num//10
print(num)

123


In [30]:
1234%10


4

In [31]:
0 * 10 + 4

4

In [32]:
1234//10

123

In [4]:
def revint(num):
    rev_num = 0
    while num > 0:
        last = num % 10
        rev_num = rev_num * 10 + last
        num = num // 10
    return rev_num
revint(1234)

4321

In [16]:
num = 1234
while num >0:
    last = num % 10
    num = num //10
    print(last,end= '')

4321

In [18]:
num = 1234
x=num//10
res=x%10
print(res)

3


In [14]:
def rev(num):
    while num >0:
        last = num % 10
        num = num //10
        #return(last,end = '')
    return(last)
rev(1234)

1

In [48]:
pow(2,4)

16

In [50]:
pow(2,4,7)

2

In [51]:
pow(2,4,6)

4

In [52]:
pow?

In [53]:
pow??

In [21]:
def form(a,age):
    if a=='married':
        print("rejected")
    else:
        if age>18:
            print("selected")
        else:
            print("age is unsatisfied")
            
form('unmarried',27)

selected


In [4]:
def fill(age,a):
    for age in range(18,30):
        if a=="married":
            print("rejected")
        elif a=="umarried":
            print("selected")
    print("age is unsatisfied")

fill('20',"unmarried")

age is unsatisfied


In [7]:
age=(input("enter age"))
a= input("enter status")
for age in range(18,30):
    if a=="married":
        print("rejected")
    elif a=="umarried":
        print("selected")
#print("age is unsatisfied")



enter age22
enter statusunmarried


In [16]:
n=12
i=1
while True:
    if i%9==0:
        print("inside if")
        break
    else:
        print("inside else")
        i=i+1
print("done")


inside else
inside else
inside else
inside else
inside else
inside else
inside else
inside else
inside if
done


In [23]:
a="join with me"
a[::-1]


'em htiw nioj'

In [25]:
b=a.split(' ')
b

['join', 'with', 'me']

In [26]:
b[::-1]

['me', 'with', 'join']

In [27]:
a

'join with me'

In [28]:
a.split(' ')[::-1]

['me', 'with', 'join']

In [1]:
l1= [1,2,3,4,5]
l2=l1.copy()
l3=l1
print(l1,l2,l3)

[1, 2, 3, 4, 5] [1, 2, 3, 4, 5] [1, 2, 3, 4, 5]


In [3]:
l1[1]=22
print(l1,l2,l3)

[1, 22, 3, 4, 5] [1, 2, 3, 4, 5] [1, 22, 3, 4, 5]


In [4]:
l3[2]=33
print(l1,l2,l3)

[1, 22, 33, 4, 5] [1, 2, 3, 4, 5] [1, 22, 33, 4, 5]


In [5]:
l2[3]=44
print(l1,l2,l3)

[1, 22, 33, 4, 5] [1, 2, 3, 44, 5] [1, 22, 33, 4, 5]


In [6]:
print(id(l1))
print(id(l2))
print(id(l3))

2404871240384
2404871240128
2404871240384


In [10]:
l4= [5,6,7,3,4,8,2,-2]
l4.sort()
l4

[-2, 2, 3, 4, 5, 6, 7, 8]

In [12]:
l5=[8,9,6,4,3,5,1,-4,-6]
sorted(l5)


[-6, -4, 1, 3, 4, 5, 6, 8, 9]

In [13]:
print(l4,l5)

[-2, 2, 3, 4, 5, 6, 7, 8] [8, 9, 6, 4, 3, 5, 1, -4, -6]


In [1]:
x= [a**2 for a in range(10)]
print(x)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [3]:
y={b:b**2 for b in range(10)}
print(y)


{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


In [2]:
def funct(func,value):
    return func(value)
def square(x):
    return x*x
result= funct(square,10)
print(result)

100


In [3]:
def add(x):
    return x+x
result=funct(add,10)
print(result)

20


In [6]:
for i in range(20):
    square=list(map(lambda x:x*x,range(i)))
    print(square)
    

[]
[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16, 25]
[0, 1, 4, 9, 16, 25, 36]
[0, 1, 4, 9, 16, 25, 36, 49]
[0, 1, 4, 9, 16, 25, 36, 49, 64]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324]


In [7]:
square=list(map(lambda x:x*x,range(20)))
print(square)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]


In [8]:
number=list(filter(lambda x:x%2==0,range(20)))
print(number)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [15]:
t=[]
for i in range(20):
    t.append(print(i,i*i))

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100
11 121
12 144
13 169
14 196
15 225
16 256
17 289
18 324
19 361


In [13]:
print(t)

[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]


In [16]:
l=tuple((i,i**2) for i in range(20))
print(l)

((0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81), (10, 100), (11, 121), (12, 144), (13, 169), (14, 196), (15, 225), (16, 256), (17, 289), (18, 324), (19, 361))


In [17]:
type(l)

tuple

In [18]:
a=list((i,i**2) for i in range(20))
print(a)

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81), (10, 100), (11, 121), (12, 144), (13, 169), (14, 196), (15, 225), (16, 256), (17, 289), (18, 324), (19, 361)]


In [19]:
type(a)

list

In [21]:
a=[]
l=[1,2,3,4,5,4,6,3,7,8,9]
for i in l:
    if i not in a:
        a.append(i)
print(a)        

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [1]:
import numpy as np
a=np.eye(4)

In [2]:
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
b=np.full([3,3],2)
print(b)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [4]:
print(np.zeros([3,4]))
print(np.ones([3,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


 print(np.array([1,2,3],[4,5,6]))

In [5]:
print(np.array([[1,2,3],[4,5,6]]))

[[1 2 3]
 [4 5 6]]


In [6]:
print(np.identity(4)) # similar as np.eye(4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
text = "Python is the most used language in top companies such as Intel, IBM, NASA, Pixar, Netflix, Facebook, JP Morgan Chase, Spotify, and many more because of its performance and its powerful libraries. To get into these companies and organizations as a Python developer, you need to master some important Python Interview Questions to crack their Python Online Assessment Round and Python Interview Round. We have prepared a list of the Top 50 Python Interview Questions along with their answers to ace interviews."

In [17]:
def count_word_frequency(text):
    # Initialize an empty dictionary to store word frequencietexts
    word_frequency = {}

    # Split the text into words
    words = text.split()

    # Count the frequency of each word
    for word in words:
        # Remove punctuation and convert to lowercase for simplicity
        cleaned_word = word.strip(".,?!").lower()

        # Update the dictionary with the word count
        if cleaned_word in word_frequency:
            word_frequency[cleaned_word] += 1     ## updating the key if already exsists
        else:
            word_frequency[cleaned_word] = 1    ## assigning the key if the key dosent exsists

    return (word_frequency)


In [18]:
word_frequency = count_word_frequency(text)
print(word_frequency)

{'python': 6, 'is': 1, 'the': 2, 'most': 1, 'used': 1, 'language': 1, 'in': 1, 'top': 2, 'companies': 2, 'such': 1, 'as': 2, 'intel': 1, 'ibm': 1, 'nasa': 1, 'pixar': 1, 'netflix': 1, 'facebook': 1, 'jp': 1, 'morgan': 1, 'chase': 1, 'spotify': 1, 'and': 4, 'many': 1, 'more': 1, 'because': 1, 'of': 2, 'its': 2, 'performance': 1, 'powerful': 1, 'libraries': 1, 'to': 4, 'get': 1, 'into': 1, 'these': 1, 'organizations': 1, 'a': 2, 'developer': 1, 'you': 1, 'need': 1, 'master': 1, 'some': 1, 'important': 1, 'interview': 3, 'questions': 2, 'crack': 1, 'their': 2, 'online': 1, 'assessment': 1, 'round': 2, 'we': 1, 'have': 1, 'prepared': 1, 'list': 1, '50': 1, 'along': 1, 'with': 1, 'answers': 1, 'ace': 1, 'interviews': 1}


In [1]:
x = "veBaBy"
x.swapcase()

'VEbAbY'

In [4]:
x

'veBaBy'

In [3]:
a = x.swapcase()
a

'VEbAbY'

In [5]:
a

'VEbAbY'

In [6]:
a[1]

'E'

In [7]:
b= 123
b

123

In [8]:
b[1]

TypeError: 'int' object is not subscriptable

In [5]:
print("hi","hi",sep = "...", end = "...")
print("hi")

hi...hi...hi


In [9]:
print("\'It\'s hero time!\' \n\t\t -Ben 10")

'It's hero time!' 
		 -Ben 10


In [10]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [2]:
print(2%10)
print(2**3**(2%10))

2
512


In [4]:
a= "Siva"
b= "siva"
print(a==b)
print(a<b)

False
True


In [10]:
#----Ascii value--------every leter in the keyborad has Ascii value
print("S:",ord("S"))
print("s:",ord("s"))
print("8:",ord("8"))
print("@:",ord("@"))
print(" :",ord(" "))

S: 83
s: 115
8: 56
@: 64
 : 32


In [11]:
#Swaping
a=4
b=5
print(a,b)
a,b = b,a
print(a,b)

4 5
5 4


In [12]:
a=5
b=10
a+=b
b=a-b
a-=b
print(a,b)

10 5


In [7]:
# String Replication
a="I can do everything with the help of jesus"
print(a*10)

I can do everything with the help of jesusI can do everything with the help of jesusI can do everything with the help of jesusI can do everything with the help of jesusI can do everything with the help of jesusI can do everything with the help of jesusI can do everything with the help of jesusI can do everything with the help of jesusI can do everything with the help of jesusI can do everything with the help of jesus 

In [ ]:
'''
input()-----always gets string type of data. if i give 5 it take it as a string not an integer
i need to do type casting to change the type of data.........int(input())...float(input())
'''

In [9]:
'''
class 
'''

class Bank_account:
    custname = ""   # ------- class variable ------ can access with class no need to create objecct
    accno = 0
    balance = 0.0
    
cust1 = Bank_account()
cust1.custname = "Suvetha"
cust1.accno = 1234
cust1.balance = 120.05

print(cust1.custname,cust1.accno,cust1.balance)    
print(Bank_account.balance)

Suvetha 1234 120.05
0.0


In [5]:
'''
__init__() method is the constructor in the python classes and its automatically called when object is created.
It is used to initialise the object's attribute.
'''
class Car:
    def __init__(self):
        self.wheels = 4    # ----- instance variable---- can't access without object
        self.airbags = 2
        self.mileage = 25.04
        
    def movefarward(self):
        print("moving!")
        
    def movebackward(self):
        print("moving back!")
        
car1 = Car()
car1.airbags = 4
car1.mileage = 20

print(car1.wheels, car1.airbags, car1.mileage)

4 4 20


In [1]:
class car:
    def __init__(self, name, no_wheels,no_airbags,mile):
        self.carname = name
        self.wheels = no_wheels
        self.airbags = no_airbags
        self.mileage = mile
        
    def __str__(self):
        return self.carname
        
    def movefarward(self,speed):
        print("moving with the speed:",speed)
        
    def movebackward(self):
        print("moving back!")
        
car2 = car("Swift",4,3,25.05)
print(car2)
print("wheels:",car2.wheels,"airbags:",car2.airbags,"mileage:",car2.mileage)
print(car2.movefarward(60))
print(car2.movebackward())

car3 = car("Inova",4,2,20.05)
print(car3)
print("wheels:",car3.wheels,"airbags:",car3.airbags,"mileage:",car3.mileage)

Swift
wheels: 4 airbags: 3 mileage: 25.05
moving with the speed: 60
None
moving back!
None
Inova
wheels: 4 airbags: 2 mileage: 20.05


In [9]:
print(getattr(car2,'airbags'))  
print(isinstance(car2,car)) 
''' getattr() fn. used to get the value of mention attribute in the object.
isinstance() fn. check if the object belongs to specific class or not and 
also check if a variable is of a certain type or not.'''

3
True


In [25]:
print(car1)   
print(car2)
print(car3)
''' when the object is created hashcode for that object is also created ------  car1 created with the code : 23C02CA3250
when i use __str__(self)------ then print the car(object) name not the code of that object
'''

Swift
Inova


' when the object is created hashcode for that object is also created ------  car1 created with the code : 23C02CA3250'

In [26]:
class bank():
    def __init__(self,name,acno,balance):
        self.name = name
        self.accno = acno
        self.balance = balance
        
    def __str__(self):
        return self.name
    
cus1= bank("Suvetha",4321,600.74)
print(cus1)
print("balance:",cus1.balance,"account_number:",cus1.accno)
cus2= bank("Jeni",5678,897.65)
print(cus2)
print("balance:",cus2.balance,"account_number:",cus2.accno)

Suvetha
balance: 600.74 account_number: 4321
Jeni
balance: 897.65 account_number: 5678


In [2]:
''' (i) ENCAPSULATION ------- Data Hiding and binding related variables and methods under the same class.
 combines variables and methods with getters and setters
 getter -------- private variable need to print outside the class with the use of getter.
 setter -------- to update the value of private variable value then use setter.'''

class car:
    def __init__(self, name, no_wheels,no_airbags,mile):
        self.carname = name
        self.__wheels = no_wheels   # ----- private variable
        self.airbags = no_airbags
        self.mileage = mile
        
    def __str__(self):
        return self.carname
        
    def movefarward(self,speed):
        print("moving with the speed:",speed)
        
    def movebackward(self):
        print("moving back!")
        
    def get_wheels(self):             #-------- getter ----- used to print the value of private variable outside the class.
        return self.__wheels
    
    def set_wheels(self,wheels_no):   #-------- setter ----- used to update the value of private variable.
        self.__wheels = wheels_no
        
c1= car("Swift",4,4,25.05)
print(c1)
print("wheels:",c1.get_wheels())    # ------- to print the private variable value then need to call the  getter method.
print("airbags:",c1.airbags,"mileage:",c1.mileage)
c1.set_wheels(8)   # -------- need to update then call the setter method.
print(c1,"wheels:",c1.get_wheels(),"airbags:",c1.airbags,"mileage:",c1.mileage)

Swift
wheels: 4
airbags: 4 mileage: 25.05
Swift wheels: 8 airbags: 4 mileage: 25.05


In [7]:
''' (ii) INHERITANCE ------ use inheritance concept to feed property from one class to another class (reusability of code)'''

# Type (I) Single Inheritance ( one parent one child)

class vehicle:    # -------------- Parent Class / main Class
    no_of_wheels = 4
    
    def forward(self):
        return "moving!"
        
class cars(vehicle):    # -------- Child Class / Sub Class
    no_of_airbags = 4
    
cs1 = cars()
print("airbags :",cs1.no_of_airbags,"wheels :",cs1.no_of_wheels)
cs1.forward()

airbags : 4 wheels : 4


'moving!'

In [9]:
# Type(II) Heirarchical Inheritance ( one parent with more child)

class vehicle:    # -------------- Parent Class / main Class
    no_of_wheels = 4
    
    def forward(self):
        return "moving!"
        
class cars(vehicle):    # -------- Child Class / Sub Class
    no_of_airbags = 4
    
class bike(vehicle):
    mileage = 40.0
    
cs1 = cars()
print("airbags :",cs1.no_of_airbags,"wheels :",cs1.no_of_wheels)
cs1.forward()
b1 = bike()
print(b1.no_of_wheels, b1.mileage)

airbags : 4 wheels : 4
4 40.0


In [10]:
# Type (III) Multi-Level Inheritance.

class vehicle:    # -------------- Parent Class / main Class
    no_of_wheels = 4
    
    def forward(self):
        return "moving!"
        
class cars(vehicle):   
    no_of_airbags = 4
    
class maruthi(cars):
    mileage = 40.0
    
m1 = maruthi()
print("airbags :",m1.no_of_airbags,"wheels :",m1.no_of_wheels,"mileage :",m1.mileage)
m1.forward()

airbags : 4 wheels : 4 mileage : 40.0


'moving!'

In [11]:
# Type (IV) Multiple Inheritancce ( two parent one child)

class vehicle:    # -------------- Parent Class / main Class
    no_of_wheels = 4
    
    def forward(self):
        return "moving!"
        
class cars(vehicle):   
    no_of_airbags = 4
    
class maruthi(cars):
    mileage = 40.0
    
class toyota(cars):
    mileage = 50.0
    
class Inova(maruthi,toyota):  # ---- same property in two parents (Diamond Property) python consider the 1st parent we mention.
    back_cam = True

c1 = Inova()
print("wheels:",c1.no_of_wheels, "airbags:", c1.no_of_airbags, "mileage:", c1.mileage,"cam:",c1.back_cam)
    

wheels: 4 airbags: 4 mileage: 40.0 cam: True


In [15]:
''' (iii) Polymorphism (same things with more form)
'''
 # Type (I) compile time Polymorphism (Method Overloading)
 # ------------- funcion overloading ---- defining multiple fn. with the same name but different parameters.   
'''
int sum(int a ,int b):
    print(a+b)
    
float sum(float a, float b):
    print(a+b)
    
int sum(int a ,int b, int c):
    print(a+b+c)
    
sum(2,3) ----- int
sum(5.6, 9.2) ----- float
sum(3,7,6) ----- sum() with 3 argument

specify with the data type and no. of argument in another languages'''

# In Python
class summation:
    def summ(self,*args):
        ans = 0 
        for i in args:
            ans += i
        return ans
    
add = summation()
print(add.summ(2,4,5,4))
print(add.summ(5,7,8,3.4,77.9))

15
101.30000000000001


In [8]:
'''
(iv) ABSTRACTION  (hiding unneccsary details and reusability)'''

from abc import ABC, abstractmethod

class car(ABC):   # ------ abstract class(kandipa indha model la dhaan intha abstract class ah use pandra class define aaghanum)
    
    @abstractmethod     # ------------ writing something with @ is named as DECORATORS
    def moveForward(self):   
        pass     # --------- method inside absract class is abstract method ----- not need to define the fn. but specify the fn.
    
    @abstractmethod
    def moveBackward(self): # ---- without defining object i can't call the method [these method are depending on the object]
        pass
    
    @staticmethod  # ------ we don't need to create object to call the class method [static method is depending on the class]
    def fm():
        pass
    
    
class inova(car):

    def moveForward(self):           # ------ without defining the abstract method we can't access it in the class
        print("moving forward!")
    
    def moveBackward(self):
        print("moving backward!")
    
    def fm():
        print("playing song!")
        

cc = inova()
cc.moveForward()

inova.fm()    #  staticmethod example ------ without define the object calling the method fm() in the class inova

moving forward!
playing song!


In [20]:
# File Handling.     'r' only for read --- 'w' can write(delete exist data and write new) --- 'a' append can add data

file = open('C:/Users/suvet/Downloads/sparkfile.txt','r')
print(file.read())  # ----- read(5) ------- reads totally as letter by letter (only 5 letter)
print(file.readline())   # ----- readline() ----- read line by line 1st line then 2nd line.
print(file.readlines())   # ------ readlines() ----- read total lines and output as list each line is each element in the list

['What is SparkContext in PySpark?\n', 'SparkContext is the entry point to interact with Apache Spark in a Python (PySpark) application. It allows you to connect to a Spark cluster and run operations on RDDs (Resilient Distributed Datasets).\n', '\n', 'It is part of the pyspark package and is required before working with low-level Spark operations.\n', 'When to Use SparkContext?\n', 'If you need low-level RDD operations.\n', 'If you are working with older versions of Spark (before 2.0).\n', 'For DataFrame operations, use SparkSession.']


In [24]:
f = open('C:/Users/suvet/Downloads/sparkfile.txt','w')
f.write("God bless you")
f.close()

In [26]:
ff = open('C:/Users/suvet/Downloads/sparkfile.txt','a')
ff.write("'What is SparkContext in PySpark?\n', 'SparkContext is the entry point to interact with Apache Spark in a Python (PySpark) application. It allows you to connect to a Spark cluster and run operations on RDDs (Resilient Distributed Datasets).\n', '\n', 'It is part of the pyspark package and is required before working with low-level Spark operations.\n', 'When to Use SparkContext?\n', 'If you need low-level RDD operations.\n', 'If you are working with older versions of Spark (before 2.0).\n', 'For DataFrame operations, use SparkSession.'")
ff.close()

In [30]:
file = open('C:/Users/suvet/Downloads/sparkfile.txt','r')
print(file.read())
file.seek(0) # once read the cursor goes to last so we can't read from 1st ----- if need to read from 1st then set seek(0) 
print(file.read())                                 # seek(0) ---- point the cursor from 1st
file.close()

God bless you'What is SparkContext in PySpark?
', 'SparkContext is the entry point to interact with Apache Spark in a Python (PySpark) application. It allows you to connect to a Spark cluster and run operations on RDDs (Resilient Distributed Datasets).
', '
', 'It is part of the pyspark package and is required before working with low-level Spark operations.
', 'When to Use SparkContext?
', 'If you need low-level RDD operations.
', 'If you are working with older versions of Spark (before 2.0).
', 'For DataFrame operations, use SparkSession.'
God bless you'What is SparkContext in PySpark?
', 'SparkContext is the entry point to interact with Apache Spark in a Python (PySpark) application. It allows you to connect to a Spark cluster and run operations on RDDs (Resilient Distributed Datasets).
', '
', 'It is part of the pyspark package and is required before working with low-level Spark operations.
', 'When to Use SparkContext?
', 'If you need low-level RDD operations.
', 'If you are workin

In [31]:
with open('C:/Users/suvet/Downloads/sparkfile.txt','r') as file:    # in this method its automatically close the file.
    print(file.read())

God bless you'What is SparkContext in PySpark?
', 'SparkContext is the entry point to interact with Apache Spark in a Python (PySpark) application. It allows you to connect to a Spark cluster and run operations on RDDs (Resilient Distributed Datasets).
', '
', 'It is part of the pyspark package and is required before working with low-level Spark operations.
', 'When to Use SparkContext?
', 'If you need low-level RDD operations.
', 'If you are working with older versions of Spark (before 2.0).
', 'For DataFrame operations, use SparkSession.'
