# Numpy
The numpy library in Python is a powerful library for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

In [1]:
#array creation
import numpy as np  #-----------------------------------ONE DIMENNSION
a=np.array([1,2,3])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.nbytes)

[1 2 3]
1
(3,)
3
4
12


In [2]:
b=np.array([[1,2,3],[4,5,6]])#------------------------TOW DIMENSION
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.itemsize)
print(b.nbytes)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
4
24


In [11]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #-----THREE DIMENSION
print(c)
print(c.ndim)
print(c.shape)
print(c.size)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)
9


In [13]:
d=np.ones([2,3],dtype=int) #-----------------------can specify the dtype,default float
print(d)

[[1 1 1]
 [1 1 1]]


In [14]:
e=np.zeros([2,3])
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
f=np.full([2,3],4)
print(f)

[[4 4 4]
 [4 4 4]]


In [19]:
g=np.eye(4)
print(g)

h=np.identity(3)
print(h)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
i=np.empty([2,3])
print(i)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
b= np.array([],dtype = int) #-------------------creating empty array
print(b)

[]


In [33]:
print(np.append(b,6))# don't channge in inplace
print(np.append(b,7))

print(b)

[6]
[7]
[]


In [5]:
a= np.array([2,4,6,8,10])
b= np.array([1,3,5,7,9])

print(a+b)
print(a*b)
print(np.dot(a,b))
print(np.mean(a))
print(np.sqrt(a))

[ 3  7 11 15 19]
[ 2 12 30 56 90]
190
6.0
[1.41421356 2.         2.44948974 2.82842712 3.16227766]


In [46]:
a=np.random.rand()#------------------gives random value between 0 and 1.......if mention any range gives empty array
print(a)
b=np.random.rand(2,3)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)
print(b.ndim)

0.7728242075097109
[[0.77605452 0.45986331 0.03503228]
 [0.91926393 0.90883222 0.67677196]]
float64
(2, 3)
6
2


In [7]:
a=np.random.randint(1,20) #---------------gives random interger with given range-----must need to specify the range else error
print(a)
print("****")
b=np.random.randint(1,24,size=(4,3))
print(b)
print("****")
c=np.random.randint(-10,10,size=(2,3))
print(c)

11
****
[[21 18  3]
 [17  9 18]
 [ 6  4 19]
 [20 19  5]]
****
[[  4  -1 -10]
 [  5  -4   1]]


In [8]:
a=np.random.normal(1,10,size=(2,2))#--------(mean,std)
print(a)
print("***")
b=np.random.normal() #------------if not mention the parameter then mean=0,std=1
print(b)

[[15.46022061 -8.37715033]
 [ 6.80914819  8.45349727]]
***
1.3819870570896633


In [10]:
a=np.random.uniform(1,10,size=(2,2))
print(a)

[[5.18570117 9.30920738]
 [8.20989213 2.32575468]]


In [4]:
a=np.random.choice([1,2,3,4,5,6])
print(a)
print("***")
b=np.random.choice([1,2,3,4,5,6,3,2],size=3,replace=True)#------------replace=True means repeated values in output
print(b)
print("***")
c=np.random.choice([1,2,3,4,5,6],size=4,replace=False)
print(c)

2
***
[1 1 1]
***
[6 5 4 3]


In [7]:
import numpy as np
d= [10,20,30,40,50,60,70,80,90,100]
p = np.percentile(d,85)
print(p)

86.5


In [8]:
from scipy.stats import skew
d = [100,90,60,80,30,50,40,10,1]
s = skew(d)
print(s)

-0.02818501518371397


In [12]:
from scipy.stats import kurtosis
d= [10,99,30,40,18,80,70,60,90,1]
k = kurtosis(d)
print(k)

-1.4211790687768922
